name: Deploy to GitHub Pages
run-name: "Running for commit: ${{ github.sha }}"
on:
  push:
    branches:
     - master


jobs:
  publish:
    concurrency: ci-${{ github.ref }}
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: haskell/actions/setup@v2
    - name: Build
      run: cabal run Start-Page-Generator
    - uses: browser-actions/setup-chrome@v1
    - name: Create screenshot
      run:  --headless --disable-gpu --screenshot=out/example.png -window-size=1280,720  ./out/index.html
    - name: Deploy 🚀
      uses: JamesIves/github-pages-deploy-action@v4
      with:
          folder: out
