name: Build, Test, and Lint
run-name: "Running for commit: ${{ github.sha }}"
on: [push, workflow_dispatch]


jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: haskell/actions/setup@v2
    - name: Build
      run: cabal build
    - name: Test
      run: cabal test

  hlint:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: 'Set up HLint'
      uses: haskell/actions/hlint-setup@v2

    - name: 'Run HLint'
      uses: haskell/actions/hlint-run@v2
      with:
        path: .
        fail-on: warning
